### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by Somethingcom515** [linus-jansson/btd6farmer#76]
how do i fix type error?

**Comment by Somethingcom515** [comment]
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Somethingcom515** [comment]
please

**Comment by Somethingcom515** [comment]
please how do I fix this?

**Comment by jonathan-gtd** [comment]
Hi,
Please give MORE details, so we can help you :)

Bye

**Comment by Somethingcom515** [comment]
C:\Users\youmu>py "C:\Users\youmu\Downloads\btd6farmer-main\src\main.py" --path "C:\Users\youmu\Downloads\btd6farmer-main\gameplans\Dark_Castle_Hard_Chimps"
Getting resolution
Traceback (most recent call last):
  File "C:\Users\youmu\Downloads\btd6farmer-main\src\main.py", line 5, in <module>
    from Bot import Bot
  File "C:\Users\youmu\Downloads\btd6farmer-main\src\Bot.py", line 14, in <module>
    import simulatedinput
  File "C:\Users\youmu\Downloads\btd6farmer-main\src\simulatedinput.py", line 32, in <module>
    def click(location: tuple | tuple, amount=1, timeout=0.5, move_timeout=0.1, hold_time=0.075, _button='left', ):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Somethingcom515** [comment]
please help

**Comment by Somethingcom515** [comment]
please

**Comment by linus-jansson** [comment]
what version of python do you have?

**Comment by Somethingcom515** [comment]
3.9.0

**Comment by Somethingcom515** [comment]
ohhhhhhhhhhhhhhhhhhh
